name: Pre-Release

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 6.dev

jobs:
  build:
    if: ${{ github.actor == 'intoeetive' }}
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_ACCESS_TOKEN }}

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: ExpressionEngine/ExpressionEngine-User-Guide
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          path: ExpressionEngine-User-Guide
          ref: 6.x

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf dependencies
        working-directory: build-tools
        run: |
          asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
          asdf install

      - name: Install build tool dependencies
        working-directory: build-tools
        run: npm install

      - name: Get version
        id: build_json
        working-directory: build-tools
        run: |
          content=`node -pe 'JSON.parse(process.argv[1]).tag' "$(cat build.json)"`
          echo "::set-output name=BUILD_VERSION::$content"

      - name: Run build process
        working-directory: build-tools
        env:
          RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          APP_REPO_PATH: ${{ github.workspace }}
          DOCS_REPO_PATH: ${{ github.workspace }}/ExpressionEngine-User-Guide
        run: gulp default --local --head --skip-lint --version=${{ steps.build_json.outputs.BUILD_VERSION }}

      - name: Archive Build files
        uses: actions/upload-artifact@v2
        with:
          name: EE${{ steps.build_json.outputs.BUILD_VERSION }}
          path: build-tools/builds

      - name: Add artifact links to pull request
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        with:
            prefix: 'Files: '
            format: name
            addTo: pull

      - name: Directory Listing on Failure
        if: failure()
        run: |
          ls -latr
          ls -latr ExpressionEngine-User-Guide
          ls -latr build-tools
          ls -latr build-tools/builds
